import type { Kelas, Siswa, Pelanggaran } from "@/types";

export const MOCK_KELAS: Kelas[] = [
    { id: 1, kelas: "X IPA 1" },
    { id: 2, kelas: "X IPS 1" },
    { id: 3, kelas: "XI IPA 1" },
    { id: 4, kelas: "XI IPS 1" },
    { id: 5, kelas: "XII IPA 1" },
];

export const MOCK_SISWA: Siswa[] = [
    {
        id: 1,
        nis: "2021001",
        nama: "Ahmad Fauzi",
        kelas_id: 1,
        jenis_kelamin: "Laki-laki",
        tanggal_lahir: "2007-05-15",
        alamat: "Jl. Merdeka No. 10",
        kelas: { id: 1, kelas: "X IPA 1" },
    },
    {
        id: 2,
        nis: "2021002",
        nama: "Budi Santoso",
        kelas_id: 1,
        jenis_kelamin: "Laki-laki",
        tanggal_lahir: "2007-08-20",
        alamat: "Jl. Sudirman No. 45",
        kelas: { id: 1, kelas: "X IPA 1" },
    },
    {
        id: 3,
        nis: "2021003",
        nama: "Dewi Lestari",
        kelas_id: 2,
        jenis_kelamin: "Perempuan",
        tanggal_lahir: "2007-11-02",
        alamat: "Jl. Mawar No. 12",
        kelas: { id: 2, kelas: "X IPS 1" },
    },
    {
        id: 4,
        nis: "2021004",
        nama: "Eko Prasetyo",
        kelas_id: 3,
        jenis_kelamin: "Laki-laki",
        tanggal_lahir: "2006-03-25",
        alamat: "Jl. Gatot Subroto No. 8",
        kelas: { id: 3, kelas: "XI IPA 1" },
    },
    {
        id: 5,
        nis: "2021005",
        nama: "Fitriani Aminah",
        kelas_id: 4,
        jenis_kelamin: "Perempuan",
        tanggal_lahir: "2006-09-14",
        alamat: "Jl. Melati No. 5",
        kelas: { id: 4, kelas: "XI IPS 1" },
    }
];

export const MOCK_PELANGGARAN: Pelanggaran[] = [
    {
        id: 1,
        siswa_id: 1,
        dilaporkan_oleh: 1,
        jenis_pelanggaran: "Terlambat Sekolah",
        tingkat: "Ringan",
        poin: 5,
        tanggal: "2026-05-10",
        waktu: "07:15",
        lokasi: "Gerbang Depan",
        deskripsi: "Siswa datang terlambat 15 menit tanpa alasan yang jelas.",
        status: "Selesai",
        tindakan: "Diberikan pembinaan oleh guru piket",
        tanggal_tindak_lanjut: "2026-05-10",
        catatan: "Siswa berjanji tidak akan terlambat lagi.",
        created_at: "2026-05-10T07:15:00Z",
        updated_at: "2026-05-10T07:30:00Z",
        url: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=800&auto=format&fit=crop",
        siswa: MOCK_SISWA[0],
    },
    {
        id: 2,
        siswa_id: 3,
        dilaporkan_oleh: 1,
        jenis_pelanggaran: "Tidak Memakai Atribut Lengkap",
        tingkat: "Ringan",
        poin: 3,
        tanggal: "2026-05-12",
        waktu: "07:05",
        lokasi: "Lapangan Upacara",
        deskripsi: "Siswa tidak memakai dasi dan topi saat upacara bendera hari Senin.",
        status: "Aktif",
        tindakan: null,
        tanggal_tindak_lanjut: null,
        catatan: null,
        created_at: "2026-05-12T07:05:00Z",
        updated_at: "2026-05-12T07:05:00Z",
        url: null,
        siswa: MOCK_SISWA[2],
    },
    {
        id: 3,
        siswa_id: 4,
        dilaporkan_oleh: 1,
        jenis_pelanggaran: "Merokok di Lingkungan Sekolah",
        tingkat: "Berat",
        poin: 50,
        tanggal: "2026-05-15",
        waktu: "12:30",
        lokasi: "Kantin Belakang",
        deskripsi: "Kedapatan merokok di belakang kantin saat jam istirahat kedua bersama siswa kelas lain.",
        status: "Aktif",
        tindakan: "Pemanggilan Orang Tua",
        tanggal_tindak_lanjut: "2026-05-16",
        catatan: "Surat perjanjian bermaterai ditandatangani orang tua dan siswa.",
        created_at: "2026-05-15T12:30:00Z",
        updated_at: "2026-05-16T10:00:00Z",
        url: "https://images.unsplash.com/photo-1527137341206-185b8823528b?q=80&w=800&auto=format&fit=crop",
        siswa: MOCK_SISWA[3],
    },
    {
        id: 4,
        siswa_id: 2,
        dilaporkan_oleh: 1,
        jenis_pelanggaran: "Keluar Kelas Tanpa Izin",
        tingkat: "Ringan",
        poin: 5,
        tanggal: "2026-05-18",
        waktu: "09:45",
        lokasi: "Kantin Sekolah",
        deskripsi: "Meninggalkan kelas saat pelajaran Fisika berlangsung tanpa meminta izin kepada guru mata pelajaran.",
        status: "Selesai",
        tindakan: "Diberikan teguran lisan",
        tanggal_tindak_lanjut: "2026-05-18",
        catatan: "Siswa segera kembali ke kelas.",
        created_at: "2026-05-18T09:45:00Z",
        updated_at: "2026-05-18T09:50:00Z",
        url: null,
        siswa: MOCK_SISWA[1],
    },
    {
        id: 5,
        siswa_id: 5,
        dilaporkan_oleh: 1,
        jenis_pelanggaran: "Membawa Handphone saat Ujian",
        tingkat: "Sedang",
        poin: 15,
        tanggal: "2026-05-19",
        waktu: "08:30",
        lokasi: "Ruang Kelas 12",
        deskripsi: "Membawa dan meletakkan handphone di laci meja selama pelaksanaan Ujian Akhir Semester.",
        status: "Aktif",
        tindakan: "Penyitaan HP selama masa ujian",
        tanggal_tindak_lanjut: "2026-05-19",
        catatan: "HP diamankan di ruang Kepala Sekolah dan hanya boleh diambil oleh orang tua.",
        created_at: "2026-05-19T08:30:00Z",
        updated_at: "2026-05-19T09:00:00Z",
        url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800&auto=format&fit=crop",
        siswa: MOCK_SISWA[4],
    }
];
